name = "Dominocraft"
mc_version = "1.20.1"

[jar]
type = "fabric"
loader = "0.16.9"
installer = "latest"

[variables]
SERVER_PORT = "25565"

[launcher]
eula_args = true
nogui = true

[markdown]
files = ["README.md"]
auto_update = false

[options]
success_line = ""
stop_command = ""

[[mods]]
type = "modrinth"
id = "PtjYWJkn"
version = "I7ggF6B5"

[[mods]]
type = "modrinth"
id = "YL57xq9U"
version = "Bi9nvICq"

[[mods]]
type = "modrinth"
id = "3dT9sgt4"
version = "4c00pjbt"

[[mods]]
type = "modrinth"
id = "uJXTNuf0"
version = "3A8FBmPP"

[[mods]]
type = "modrinth"
id = "x3HZvrj6"
version = "vq5NtpQQ"

[[mods]]
type = "modrinth"
id = "54eqfZSC"
version = "q3oqxRHM"

[[mods]]
type = "modrinth"
id = "rLLJ1OZM"
version = "7tRnsYkP"

[[mods]]
type = "modrinth"
id = "ZYgyPyfq"
version = "pfVTUz1L"

[[mods]]
type = "modrinth"
id = "FNi5IMiX"
version = "629Wolcf"

[[mods]]
type = "modrinth"
id = "oNB5jhlA"
version = "xDgS8MD5"

[[mods]]
type = "modrinth"
id = "Ht4BfYp6"
version = "hvfjXu8d"

[[mods]]
type = "modrinth"
id = "yHf7SALy"
version = "5lHXCowj"

[[mods]]
type = "modrinth"
id = "HJetCzWo"
version = "Dsk6WutR"

[[mods]]
type = "modrinth"
id = "OVuFYfre"
version = "i3v1Skck"

[[mods]]
type = "modrinth"
id = "fQEb0iXm"
version = "jiDwS0W1"

[[mods]]
type = "modrinth"
id = "6FtRfnLg"
version = "CuLlUIYD"

[[mods]]
type = "modrinth"
id = "yBW8D80W"
version = "mYl4RvKg"

[[mods]]
type = "modrinth"
id = "Wb5oqrBJ"
version = "fKY4vKuA"

[[mods]]
type = "modrinth"
id = "qwbArkQk"
version = "benCZTIU"

[[mods]]
type = "modrinth"
id = "BUpChT1v"
version = "BvZZmYcB"

[[mods]]
type = "modrinth"
id = "IAnP4np7"
version = "nqsTHZwx"

[[mods]]
type = "modrinth"
id = "kawJN2LZ"
version = "BbKorFuj"

[[mods]]
type = "modrinth"
id = "xv94TkTM"
version = "6ipZLQSK"

[[mods]]
type = "modrinth"
id = "3JQDJrYW"
version = "oG5DC7IV"

[[mods]]
type = "modrinth"
id = "e9V6wFcR"
version = "4KEfJPHI"

[[mods]]
type = "modrinth"
id = "t5FRdP87"
version = "lYpHN3iF"

[[mods]]
type = "modrinth"
id = "Dk6su9JN"
version = "UdH7Njsc"

[[mods]]
type = "modrinth"
id = "MS1ZMyR7"
version = "FbxcDBxy"

[[mods]]
type = "modrinth"
id = "hB899VmG"
version = "LB4dHaVf"

[[mods]]
type = "modrinth"
id = "o1C1Dkj5"
version = "nidyvq2m"

[[mods]]
type = "modrinth"
id = "Bh37bMuy"
version = "Rc9pkPug"

[[mods]]
type = "modrinth"
id = "AANobbMI"
version = "ygf8cVZg"

[[mods]]
type = "modrinth"
id = "5aaWibi9"
version = "AHxQGtuC"

[[mods]]
type = "modrinth"
id = "JrvR9OHr"
version = "K8M8C81n"

[[mods]]
type = "modrinth"
id = "GmjmRQ0A"
version = "EzpVcwYV"

[[mods]]
type = "modrinth"
id = "dOGM7ccu"
version = "cmqFoINR"

[[mods]]
type = "modrinth"
id = "lhGA9TYQ"
version = "WbL7MStR"

[[mods]]
type = "modrinth"
id = "OsZiaDHq"
version = "Ex1iqbF5"

[[mods]]
type = "modrinth"
id = "w7ThoJFB"
version = "RW06GEHk"

[[mods]]
type = "modrinth"
id = "1eAoo2KR"
version = "yDSgD8Iz"

[[mods]]
type = "modrinth"
id = "P7dR8mSH"
version = "P7uGFii0"

[[mods]]
type = "modrinth"
id = "g4bSYbrU"
version = "7VLMSyNv"

[[mods]]
type = "modrinth"
id = "hvFnDODi"
version = "4SHylIO9"

[[mods]]
type = "modrinth"
id = "GyKzAh3l"
version = "Ae00krmR"

[[mods]]
type = "modrinth"
id = "Ha28R6CL"
version = "csX9r2wS"

[[mods]]
type = "modrinth"
id = "G1hIVOrD"
version = "UOdaYbhh"

[[mods]]
type = "modrinth"
id = "G1s2WpNo"
version = "1yJzEpzh"

[[mods]]
type = "modrinth"
id = "H9tVki0G"
version = "SqoQfcGh"

[[mods]]
type = "modrinth"
id = "aC3cM3Vq"
version = "mjuG4AYd"

[[mods]]
type = "modrinth"
id = "ohNO6lps"
version = "Qs8LaZLo"

[[mods]]
type = "modrinth"
id = "LQ3K71Q1"
version = "kIWCy30o"

[[mods]]
type = "modrinth"
id = "ziOp6EO8"
version = "Gnum5EJm"

[[mods]]
type = "modrinth"
id = "QwxR6Gcd"
version = "6XDJoCks"

[[mods]]
type = "modrinth"
id = "NRjRiSSD"
version = "5xvCCRjJ"

[[mods]]
type = "modrinth"
id = "uy4Cnpcm"
version = "CBnLZwRS"

[[mods]]
type = "modrinth"
id = "z9Ve58Ih"
version = "6LPrzuB0"

[[mods]]
type = "modrinth"
id = "Ua7DFN59"
version = "lscV1N5k"

[[mods]]
type = "modrinth"
id = "2rL16t1O"
version = "PBk4PKui"

[[mods]]
type = "modrinth"
id = "nmDcB62a"
version = "rBUcyf7J"

[[mods]]
type = "modrinth"
id = "tagwiZkJ"
version = "z88tNWJh"

[[mods]]
type = "modrinth"
id = "Eh11TaTm"
version = "BtUrY6MK"

[[mods]]
type = "modrinth"
id = "8oi3bsk5"
version = "WeYhEb5d"

[[mods]]
type = "modrinth"
id = "CXd6g9xp"
version = "rdFxc9mZ"

[[mods]]
type = "modrinth"
id = "9eGKb6K1"
version = "IZhZbWUU"

[[mods]]
type = "modrinth"
id = "egyqODDj"
version = "nxtkgmc5"

[[mods]]
type = "modrinth"
id = "ZVzW5oNS"
version = "uUqarp2H"

[[mods]]
type = "modrinth"
id = "u6dRKJwZ"
version = "AFNTMB1o"

[[mods]]
type = "modrinth"
id = "kidLKymU"
version = "yV6hn0bB"

[[mods]]
type = "modrinth"
id = "gvQqBUqZ"
version = "ZSNsJrPI"

[[mods]]
type = "modrinth"
id = "SNVQ2c0g"
version = "iug2Tybf"

[[mods]]
type = "modrinth"
id = "51shyZVL"
version = "3m5znPWm"

[[mods]]
type = "modrinth"
id = "MBAkmtvl"
version = "SdRZPngG"

[[mods]]
type = "modrinth"
id = "8YcE8y4T"
version = "RLSQKSBU"

[[mods]]
type = "modrinth"
id = "IwCkru1D"
version = "vQa9oDJZ"

[[mods]]
type = "modrinth"
id = "F8BQNPWX"
version = "dMGBsRgz"

[[mods]]
type = "modrinth"
id = "QdG47OkI"
version = "GkLb4bRl"

[[mods]]
type = "modrinth"
id = "Z2mXHnxP"
version = "FL88RLRu"

[[mods]]
type = "modrinth"
id = "fuuu3xnx"
version = "eh4IBlu2"

[[mods]]
type = "modrinth"
id = "NNAgCjsB"
version = "naHGCw23"

[[mods]]
type = "modrinth"
id = "pJmCFF0p"
version = "NRw0CDAc"

[[mods]]
type = "modrinth"
id = "nvQzSEkH"
version = "Lvyx1o7I"

[[mods]]
type = "modrinth"
id = "XNlO7sBv"
version = "1Z9HNWpj"

[[mods]]
type = "modrinth"
id = "H8CaAYZC"
version = "XGIsoVGT"

[[mods]]
type = "modrinth"
id = "IYY9Siz8"
version = "vVYtBiuW"

[[mods]]
type = "modrinth"
id = "4XJZeZbM"
version = "kD7KNe4P"

[[mods]]
type = "modrinth"
id = "QAGBst4M"
version = "qjSRRf2B"

[[mods]]
type = "modrinth"
id = "fgmhI8kH"
version = "tpKHcPzx"

[[mods]]
type = "modrinth"
id = "LPjGiSO4"
version = "QsRKydVt"

[[mods]]
type = "modrinth"
id = "P4PAsklC"
version = "n22gCKB8"

[[mods]]
type = "modrinth"
id = "M1953qlQ"
version = "PlEObkl9"

[[mods]]
type = "modrinth"
id = "P0Mu4wcQ"
version = "ddhoLf22"

[[mods]]
type = "modrinth"
id = "Wnxd13zP"
version = "hefSwtn6"

[[mods]]
type = "modrinth"
id = "ZcR9weSm"
version = "jwS20yNo"

[[mods]]
type = "modrinth"
id = "9s6osm5g"
version = "2xQdCMyG"

[[mods]]
type = "modrinth"
id = "TEzJJY7H"
version = "m9j7sYEQ"

[[mods]]
type = "modrinth"
id = "Xbc0uyRg"
version = "7Ub71nPb"

[[mods]]
type = "modrinth"
id = "b7NV2plI"
version = "Ffbl3z7g"

[[mods]]
type = "modrinth"
id = "LOpKHB2A"
version = "FOC8o94m"

[[mods]]
type = "modrinth"
id = "HjmxVlSr"
version = "qLnQnqXS"

[[mods]]
type = "modrinth"
id = "EsAfCjCV"
version = "xcauwnEB"

[[mods]]
type = "modrinth"
id = "CdRC4fyI"
version = "qWJ0YcQq"

[[mods]]
type = "modrinth"
id = "uXXizFIs"
version = "unerR5MN"

[[mods]]
type = "modrinth"
id = "iYVih5qu"
version = "DaaIQvYx"

[[mods]]
type = "modrinth"
id = "laNoi025"
version = "OyLhWReL"

[[mods]]
type = "modrinth"
id = "oL18adaQ"
version = "YoXl9tp0"

[[mods]]
type = "modrinth"
id = "1IjD5062"
version = "qGTDcjHM"

[[mods]]
type = "modrinth"
id = "POQ2i9zu"
version = "7H0cR4ue"

[[mods]]
type = "modrinth"
id = "1bokaNcj"
version = "jouP2Oob"

[[mods]]
type = "modrinth"
id = "vuGFx44e"
version = "o4CYZoEP"

[[mods]]
type = "modrinth"
id = "x3s69afN"
version = "Q4DJyoRR"

[[mods]]
type = "modrinth"
id = "e0M1UDsY"
version = "aNzU64AT"

[[mods]]
type = "modrinth"
id = "rcTfTZr3"
version = "k0t6DSmw"

[[mods]]
type = "modrinth"
id = "l9fldtN4"
version = "hwClzDIs"

[[mods]]
type = "modrinth"
id = "mOgUt4GM"
version = "lEkperf6"

[[mods]]
type = "modrinth"
id = "ZouiUX7t"
version = "EoAqSkiW"

[[mods]]
type = "modrinth"
id = "7vxePowz"
version = "Ms2QOr1b"

[[mods]]
type = "modrinth"
id = "MI1LWe93"
version = "Mw0Hq1SZ"

[[mods]]
type = "modrinth"
id = "XaDC71GB"
version = "KSbGuaNO"

[[mods]]
type = "modrinth"
id = "fM515JnW"
version = "KRg74QMN"

[[mods]]
type = "modrinth"
id = "Lq6ojcWv"
version = "4oiJql9P"

[[mods]]
type = "modrinth"
id = "NcUtCpym"
version = "VXCG8MnU"

[[mods]]
type = "modrinth"
id = "8BmcQJ2H"
version = "9VG3hx3F"

[[mods]]
type = "modrinth"
id = "UVtY3ZAC"
version = "LeAiyr1s"

[[mods]]
type = "modrinth"
id = "qANg5Jrr"
version = "ul9OslWB"

[[mods]]
type = "modrinth"
id = "1DWmBJVA"
version = "JKjZUzrO"

[[mods]]
type = "modrinth"
id = "Orvt0mRa"
version = "gofbpynL"

[[mods]]
type = "modrinth"
id = "Cnejf5xM"
version = "4UWabEWo"

[[mods]]
type = "modrinth"
id = "qyVF9oeo"
version = "hxEab3Tk"

[[mods]]
type = "modrinth"
id = "ECOSu6pa"
version = "D9jX5JX6"

[[mods]]
type = "modrinth"
id = "qQpWCN75"
version = "QM70Gb46"

[[mods]]
type = "modrinth"
id = "Yd4wb5wZ"
version = "aUJDlQHP"
