# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.block_entities]

			[light_sources.settings.block_entities.minecraft]
				bed = true
				calibrated_sculk_sensor = true
				furnace = true
				dropper = true
				daylight_detector = true
				sign = true
				jukebox = true
				brewing_stand = true
				sculk_sensor = true
				hanging_sign = true
				brushable_block = true
				conduit = true
				beehive = true
				dispenser = true
				smoker = true
				lectern = true
				skull = true
				campfire = true
				barrel = true
				chest = true
				piston = true
				sculk_shrieker = true
				end_portal = true
				shulker_box = true
				enchanting_table = true
				banner = true
				structure_block = true
				sculk_catalyst = true
				ender_chest = true
				bell = true
				end_gateway = true
				comparator = true
				beacon = true
				command_block = true
				jigsaw = true
				hopper = true
				mob_spawner = true
				chiseled_bookshelf = true
				trapped_chest = true
				decorated_pot = true
				blast_furnace = true

			[light_sources.settings.block_entities.farmersdelight]
				basket = true
				canvas_sign = true
				stove = true
				cutting_board = true
				hanging_canvas_sign = true
				skillet = true
				cabinet = true
				cooking_pot = true

			[light_sources.settings.block_entities.camping]
				enderpack = true
				backpack = true
				grill = true

			[light_sources.settings.block_entities.handcrafted]
				container = true
				oven = true
				crockery = true

			[light_sources.settings.block_entities.bakery]
				small_cooking_pot = true

			[light_sources.settings.block_entities.vinery]
				basket = true
				mod_sign = true
				fermentation_barrel = true
				apple_press = true
				vinery_standard = true
				flower_pot = true
				storage = true
				cabinet = true
				mod_hanging_sign = true

			[light_sources.settings.block_entities.herbalbrews]
				tea_kettle = true
				cauldron = true
				tea_leaf = true

			[light_sources.settings.block_entities.beachparty]
				mini_fridge = true
				tiki_bar = true

			[light_sources.settings.block_entities.weeping_angels]
				snow_angel = true
				statue = true
				generator = true
				coffin = true

			[light_sources.settings.block_entities.exposure]
				lightroom = true
				flash = true

			[light_sources.settings.block_entities.furniture]
				coffer = true
				gramophone = true
				chimney = true
				fish_tank = true
				display = true
				dresser = true
				grandfather_clock = true
				clock = true
				cabinet = true

			[light_sources.settings.block_entities.candlelight]
				dinner_bell = true
				sideboard = true
				cooking_pan = true
				effect_food_block = true
				stove_block = true
				cooking_pot = true
				type_writer = true

			[light_sources.settings.block_entities.brewery]
				brewingstation = true
				beer_mug = true

			[light_sources.settings.block_entities.create]
				clockwork_bearing = true
				funnel = true
				hand_crank = true
				simple_kinetic = true
				clipboard = true
				rope_pulley = true
				harvester = true
				display_link = true
				lectern_controller = true
				encased_shaft = true
				item_drain = true
				belt = true
				backtank = true
				chassis = true
				gantry_pinion = true
				steam_engine = true
				clutch = true
				toolbox = true
				fake_track = true
				cuckoo_clock = true
				track_observer = true
				peculiar_bell = true
				motor = true
				pulse_extender = true
				elevator_contact = true
				sequenced_gearshift = true
				crushing_wheel = true
				mechanical_roller = true
				spout = true
				gearbox = true
				stockpile_switch = true
				powered_shaft = true
				andesite_tunnel = true
				stressometer = true
				smart_chute = true
				sticker = true
				encased_large_cogwheel = true
				nixie_tube = true
				water_wheel = true
				mechanical_piston = true
				mechanical_press = true
				bogey = true
				track_signal = true
				smart_fluid_pipe = true
				portable_storage_interface = true
				crushing_wheel_controller = true
				pulse_repeater = true
				mechanical_bearing = true
				depot = true
				schematicannon = true
				chute = true
				sliding_door = true
				fluid_pipe = true
				encased_cogwheel = true
				mechanical_crafter = true
				copycat = true
				cursed_bell = true
				hose_pulley = true
				rotation_speed_controller = true
				creative_crate = true
				basin = true
				encased_fluid_pipe = true
				fluid_valve = true
				brass_tunnel = true
				fluid_tank = true
				schematic_table = true
				portable_fluid_interface = true
				analog_lever = true
				adjustable_chain_gearshift = true
				windmill_bearing = true
				speedometer = true
				millstone = true
				creative_fluid_tank = true
				flap_display = true
				turntable = true
				gantry_shaft = true
				mechanical_arm = true
				item_vault = true
				blaze_heater = true
				flywheel = true
				weighted_ejector = true
				content_observer = true
				deployer = true
				track = true
				track_station = true
				elevator_pulley = true
				saw = true
				drill = true
				valve_handle = true
				mechanical_pump = true
				mechanical_mixer = true
				nozzle = true
				cart_assembler = true
				steam_whistle = true
				large_water_wheel = true
				encased_fan = true
				glass_fluid_pipe = true
				gearshift = true
				contraption_controls = true
				redstone_link = true
				placard = true

			[light_sources.settings.block_entities.farm_and_charm]
				mincer = true
				crafting_bowl = true
				effect_food_block = true
				stove_block = true
				feeding_trough = true
				water_sprinkler = true
				silo = true
				cooking_pot = true
				scarecrow = true
				roaster = true

			[light_sources.settings.block_entities.doapi]
				standard = true
				flower_box = true
				sideboard = true
				flower_pot = true
				storage = true
				cabinet = true

			[light_sources.settings.block_entities.waystones]
				sharestone = true
				portstone = true
				warp_plate = true
				waystone = true

			[light_sources.settings.block_entities.xercamusic]
				metronome = true
				music_box = true

			[light_sources.settings.block_entities.sliceanddice]
				slicer = true
				sprinkler = true

			[light_sources.settings.block_entities.expandeddelight]
				juicer = true

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				zombie_horse = true
				axolotl = true
				egg = true
				zoglin = true
				spawner_minecart = true
				allay = true
				llama = true
				mule = true
				bat = true
				husk = true
				camel = true
				experience_bottle = true
				rabbit = true
				firework_rocket = true
				silverfish = true
				giant = true
				drowned = true
				item = true
				goat = true
				horse = true
				vindicator = true
				minecart = true
				spectral_arrow = true
				llama_spit = true
				mooshroom = true
				glow_item_frame = false
				snowball = true
				tnt = true
				parrot = true
				creeper = true
				lightning_bolt = true
				tadpole = true
				ravager = true
				evoker_fangs = true
				tropical_fish = true
				chest_minecart = true
				slime = true
				pillager = true
				area_effect_cloud = true
				blaze = true
				piglin = true
				end_crystal = true
				endermite = true
				zombie = true
				ender_pearl = true
				item_display = true
				guardian = true
				fireball = true
				illusioner = true
				eye_of_ender = true
				wither_skull = true
				wolf = true
				zombie_villager = true
				tnt_minecart = true
				block_display = true
				elder_guardian = true
				chest_boat = true
				boat = true
				small_fireball = true
				strider = true
				cave_spider = true
				witch = true
				cod = true
				snow_golem = true
				spider = true
				command_block_minecart = true
				panda = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				frog = true
				hoglin = true
				armor_stand = true
				experience_orb = true
				dolphin = true
				stray = true
				turtle = true
				shulker = true
				salmon = true
				wither_skeleton = true
				vex = true
				wandering_trader = true
				piglin_brute = true
				ocelot = true
				furnace_minecart = true
				item_frame = true
				phantom = true
				ender_dragon = true
				leash_knot = true
				evoker = true
				marker = true
				glow_squid = true
				warden = true
				squid = true
				shulker_bullet = true
				enderman = true
				dragon_fireball = true
				chicken = true
				sniffer = true
				trader_llama = true
				donkey = true
				fox = true
				iron_golem = true
				zombified_piglin = true
				cat = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				villager = true
				skeleton_horse = true
				fishing_bobber = true
				text_display = true
				polar_bear = true
				hopper_minecart = true
				falling_block = true
				painting = true
				interaction = true
				wither = true

			[light_sources.settings.entities.farmersdelight]
				rotten_tomato = true

			[light_sources.settings.entities.crittersandcompanions]
				dragonfly = true
				leaf_insect = true
				jumping_spider = true
				shima_enaga = true
				koi_fish = true
				dumbo_octopus = true
				grappling_hook = true
				ferret = true
				otter = true
				sea_bunny = true
				red_panda = true

			[light_sources.settings.entities.handcrafted]
				seat = true
				fancy_painting = true

			[light_sources.settings.entities.endermanoverhaul]
				flower_fields_enderman = true
				coral_enderman = true
				windswept_hills_enderman = true
				ender_bullet = true
				icy_pearl = true
				summoner_pearl = true
				nether_wastes_enderman = true
				soul_pearl = true
				mushroom_fields_enderman = true
				snowy_enderman = true
				soulsand_valley_enderman = true
				axolotl_pet_enderman = true
				hammerhead_pet_enderman = true
				savanna_enderman = true
				ice_spikes_enderman = true
				desert_enderman = true
				spirit = true
				ancient_pearl = true
				end_enderman = true
				corrupted_pearl = true
				crimson_forest_enderman = true
				bubble_pearl = true
				warped_pearl = true
				cave_enderman = true
				dark_oak_enderman = true
				crimson_pearl = true
				swamp_enderman = true
				end_islands_enderman = true
				scarab = true
				badlands_enderman = true
				warped_forest_enderman = true
				pet_enderman = true

			[light_sources.settings.entities.bakery]
				wandering_baker = true

			[light_sources.settings.entities.niftycarts]
				plow = true
				supply_cart = true
				postilion = true
				hand_cart = true
				animal_cart = true

			[light_sources.settings.entities.vinery]
				mule = true
				dark_cherry_boat = true
				chair = true
				dark_cherry_chest_boat = true
				wandering_winemaker = true

			[light_sources.settings.entities.creeperoverhaul]
				swamp_creeper = true
				bamboo_creeper = true
				jungle_creeper = true
				cave_creeper = true
				beach_creeper = true
				savannah_creeper = true
				spruce_creeper = true
				hills_creeper = true
				snowy_creeper = true
				badlands_creeper = true
				ocean_creeper = true
				dark_oak_creeper = true
				desert_creeper = true
				dripstone_creeper = true
				mushroom_creeper = true

			[light_sources.settings.entities.weeping_angels]
				generator = true
				weeping_angel = true

			[light_sources.settings.entities.beachparty]
				coconut = true

			[light_sources.settings.entities.naturalist]
				deer = true
				snail = true
				alligator = true
				rhino = true
				bluejay = true
				snake = true
				catfish = true
				boar = true
				robin = true
				caterpillar = true
				dragonfly = true
				duck_egg = true
				tortoise = true
				butterfly = true
				duck = true
				bear = true
				sparrow = true
				lizard = true
				rattlesnake = true
				zebra = true
				canary = true
				firefly = true
				hippo = true
				coral_snake = true
				cardinal = true
				lion = true
				vulture = true
				bass = true
				giraffe = true
				lizard_tail = true
				elephant = true
				finch = true

			[light_sources.settings.entities.exposure]
				photograph = true
				photograph_frame = true

			[light_sources.settings.entities.furniture]
				canvas = true
				fake_fish_tank = true
				chair = true
				pells = true

			[light_sources.settings.entities.immersive_aircraft]
				airship = true
				cargo_airship = true
				warship = true
				gyrodyne = true
				quadrocopter = true
				biplane = true
				tiny_tnt = true
				bullet = true

			[light_sources.settings.entities.ribbits]
				ribbit = true

			[light_sources.settings.entities.brewery]
				beer_elemental = true
				hanging_rope = true
				dark_brew = true
				rope_knot = true
				beer_elemental_attack = true
				rope_collision = true

			[light_sources.settings.entities.create]
				carriage_contraption = true
				seat = true
				stationary_contraption = true
				contraption = true
				gantry_contraption = true
				super_glue = true
				crafting_blueprint = true
				potato_projectile = true

			[light_sources.settings.entities.farm_and_charm]
				plow = true
				rotten_tomato = true
				chest_cart = true

			[light_sources.settings.entities.doapi]
				chair = true

			[light_sources.settings.entities.terraform]
				chest_boat = true
				boat = true

			[light_sources.settings.entities.xercamusic]
				music_spirit = true

			[light_sources.settings.entities.friendsandfoes]
				glare = true
				copper_golem = true
				player_illusion = true
				ice_chunk = true
				moobloom = true
				tuff_golem = true
				mauler = true
				iceologer = true
				wildfire = true
				crab = true
				rascal = true

			[light_sources.settings.entities.artifacts]
				mimic = true

